# -*- coding: utf-8 -*-
"""Minimum Öklid Mesafesinin Hesaplanması.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iqzB59yJD149cPjHNdpsPs0uu-23NjRt
"""

import math

# Noktaların tanımlanması
points = [(1, 2), (3, 4), (5, 6), (7, 8)]  # Örnek olarak 4 nokta tanımladım

# Öklid mesafesi için bir fonksiyon yazma
def euclideanDistance(point1, point2):
    x1, y1 = point1
    x2, y2 = point2
    return math.sqrt((x2 - x1) ** 2 + (y2 - y1) ** 2)

# Mesafelerin hesaplanması
distances = []
for i in range(len(points)):
    for j in range(i+1, len(points)):
        distance = euclideanDistance(points[i], points[j])
        distances.append(distance)

# Minimum mesafenin bulunması
min_distance = min(distances)
print("Minimum mesafe:", min_distance)